//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/nfs/homes/lannur-s/42/42MiniShell/docs/JollyShellLexer.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class JollyShellLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WORD=1, VARIABLE=2, IO_NUMBER=3, ASSIGNMENT_WORD=4, PIPE=5, REDIRECT_IN=6, 
		REDIRECT_OUT=7, HEREDOC=8, APPEND_OUT=9, DOUBLE_QUOTED_STRING=10, LINEBREAK=11;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"WORD", "VARIABLE", "IO_NUMBER", "ASSIGNMENT_WORD", "PIPE", "REDIRECT_IN", 
		"REDIRECT_OUT", "HEREDOC", "APPEND_OUT", "DOUBLE_QUOTED_STRING", "LINEBREAK"
	};


	public JollyShellLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JollyShellLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, "'='", "'|'", "'<'", "'>'", "'<<'", "'>>'", null, 
		"'\\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WORD", "VARIABLE", "IO_NUMBER", "ASSIGNMENT_WORD", "PIPE", "REDIRECT_IN", 
		"REDIRECT_OUT", "HEREDOC", "APPEND_OUT", "DOUBLE_QUOTED_STRING", "LINEBREAK"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JollyShellLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static JollyShellLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,11,63,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,1,0,4,0,25,8,0,11,0,12,0,26,1,1,1,1,
		1,1,1,2,4,2,33,8,2,11,2,12,2,34,1,3,1,3,1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,
		7,1,7,1,8,1,8,1,8,1,9,1,9,1,9,1,9,5,9,55,8,9,10,9,12,9,58,9,9,1,9,1,9,
		1,10,1,10,0,0,11,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,1,
		0,3,4,0,48,57,65,90,95,95,97,122,1,0,48,57,3,0,10,10,13,13,92,92,66,0,
		1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,
		0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,1,24,
		1,0,0,0,3,28,1,0,0,0,5,32,1,0,0,0,7,36,1,0,0,0,9,38,1,0,0,0,11,40,1,0,
		0,0,13,42,1,0,0,0,15,44,1,0,0,0,17,47,1,0,0,0,19,50,1,0,0,0,21,61,1,0,
		0,0,23,25,7,0,0,0,24,23,1,0,0,0,25,26,1,0,0,0,26,24,1,0,0,0,26,27,1,0,
		0,0,27,2,1,0,0,0,28,29,5,36,0,0,29,30,3,1,0,0,30,4,1,0,0,0,31,33,7,1,0,
		0,32,31,1,0,0,0,33,34,1,0,0,0,34,32,1,0,0,0,34,35,1,0,0,0,35,6,1,0,0,0,
		36,37,5,61,0,0,37,8,1,0,0,0,38,39,5,124,0,0,39,10,1,0,0,0,40,41,5,60,0,
		0,41,12,1,0,0,0,42,43,5,62,0,0,43,14,1,0,0,0,44,45,5,60,0,0,45,46,5,60,
		0,0,46,16,1,0,0,0,47,48,5,62,0,0,48,49,5,62,0,0,49,18,1,0,0,0,50,56,5,
		34,0,0,51,55,8,2,0,0,52,53,5,92,0,0,53,55,9,0,0,0,54,51,1,0,0,0,54,52,
		1,0,0,0,55,58,1,0,0,0,56,54,1,0,0,0,56,57,1,0,0,0,57,59,1,0,0,0,58,56,
		1,0,0,0,59,60,5,34,0,0,60,20,1,0,0,0,61,62,5,10,0,0,62,22,1,0,0,0,5,0,
		26,34,54,56,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
